name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.7.0
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py=2.10.0
    - eventlet
    - flask-socketio=3.0.1
    - python-socketio=3.0.0
    - python-engineio=3.0.0
    - seaborn
    - pandas
    - opencv
    - ffmpeg
    - imageio
    - pyqt=4.11.4
    - pip:
        - moviepy
        - requests
        - tensorflow-directml
